// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3t_m2sEd-sVoPOb_rIIpLNgCikfN_7xE',
    appId: '1:684171435154:web:b3b0554bee527beb381a4b',
    messagingSenderId: '684171435154',
    projectId: 'aidwise-2b52f',
    authDomain: 'aidwise-2b52f.firebaseapp.com',
    storageBucket: 'aidwise-2b52f.firebasestorage.app',
    measurementId: 'G-YCJE3H63Q7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB8Z40uMPnWAICbFRmMnJN9FGdtXXMYLA',
    appId: '1:684171435154:android:8658c7b8ccaa5121381a4b',
    messagingSenderId: '684171435154',
    projectId: 'aidwise-2b52f',
    storageBucket: 'aidwise-2b52f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2lHUQZBZrEbopwwQRbhJdiunbqcV_WSk',
    appId: '1:684171435154:ios:130e62384fd6f0e0381a4b',
    messagingSenderId: '684171435154',
    projectId: 'aidwise-2b52f',
    storageBucket: 'aidwise-2b52f.firebasestorage.app',
    iosBundleId: 'com.example.aidwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2lHUQZBZrEbopwwQRbhJdiunbqcV_WSk',
    appId: '1:684171435154:ios:130e62384fd6f0e0381a4b',
    messagingSenderId: '684171435154',
    projectId: 'aidwise-2b52f',
    storageBucket: 'aidwise-2b52f.firebasestorage.app',
    iosBundleId: 'com.example.aidwise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3t_m2sEd-sVoPOb_rIIpLNgCikfN_7xE',
    appId: '1:684171435154:web:1eb5858dada94c04381a4b',
    messagingSenderId: '684171435154',
    projectId: 'aidwise-2b52f',
    authDomain: 'aidwise-2b52f.firebaseapp.com',
    storageBucket: 'aidwise-2b52f.firebasestorage.app',
    measurementId: 'G-PSGBDKTYV8',
  );
}
