// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQJHRvBUJTAqqyOLHttXZvK3g4fwt4B_E',
    appId: '1:156490799679:web:11cf9ae7547cacf485368a',
    messagingSenderId: '156490799679',
    projectId: 'aidwise-cmd-center-v2',
    authDomain: 'aidwise-cmd-center-v2.firebaseapp.com',
    storageBucket: 'aidwise-cmd-center-v2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBV34VkeaZL-8Lx9PqcskmiP8XDudXers',
    appId: '1:156490799679:android:3cba54466bfcab9085368a',
    messagingSenderId: '156490799679',
    projectId: 'aidwise-cmd-center-v2',
    storageBucket: 'aidwise-cmd-center-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV5EwULS15OA4mdsNFBf7qbmsM0PGNEyo',
    appId: '1:156490799679:ios:c6ab50f5417bd46a85368a',
    messagingSenderId: '156490799679',
    projectId: 'aidwise-cmd-center-v2',
    storageBucket: 'aidwise-cmd-center-v2.firebasestorage.app',
    iosBundleId: 'com.example.aidwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV5EwULS15OA4mdsNFBf7qbmsM0PGNEyo',
    appId: '1:156490799679:ios:c6ab50f5417bd46a85368a',
    messagingSenderId: '156490799679',
    projectId: 'aidwise-cmd-center-v2',
    storageBucket: 'aidwise-cmd-center-v2.firebasestorage.app',
    iosBundleId: 'com.example.aidwise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQJHRvBUJTAqqyOLHttXZvK3g4fwt4B_E',
    appId: '1:156490799679:web:0d7012b8644bcc1a85368a',
    messagingSenderId: '156490799679',
    projectId: 'aidwise-cmd-center-v2',
    authDomain: 'aidwise-cmd-center-v2.firebaseapp.com',
    storageBucket: 'aidwise-cmd-center-v2.firebasestorage.app',
  );
}
