import 'dart:ui';
import 'package:flutter/material.dart';
import '../theme/app_theme.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

import 'report_detail_map_screen.dart';
import '../services/auth_service.dart';
import '../services/ai_service.dart';

class HeatmapDashboard extends StatefulWidget {
  final bool showAppBar;
  
  const HeatmapDashboard({super.key, this.showAppBar = true});

  @override
  State<HeatmapDashboard> createState() => _HeatmapDashboardState();
}

class _HeatmapDashboardState extends State<HeatmapDashboard> {
  bool _isLoadingSummary = false;

  void _showAISummary() async {
    setState(() => _isLoadingSummary = true);
    
    try {
      // Fetch all open reports
      final reportsSnap = await FirebaseFirestore.instance
          .collection('reports').where('status', isEqualTo: 'Open').get();
      final openReports = reportsSnap.docs.map((d) => d.data()).toList();
      
      // Fetch volunteer count
      final volSnap = await FirebaseFirestore.instance
          .collection('users').where('role', isEqualTo: 'Volunteer').get();
      
      final summary = await AIService.generateSituationSummary(openReports, volSnap.docs.length);
      
      if (mounted) {
        setState(() => _isLoadingSummary = false);
        showDialog(
          context: context,
          builder: (ctx) => Dialog(
            backgroundColor: Colors.transparent,
            child: Container(
              padding: const EdgeInsets.all(24),
              decoration: BoxDecoration(
                color: AppTheme.surface,
                borderRadius: BorderRadius.circular(20),
                border: Border.all(color: AppTheme.primary.withValues(alpha: 0.4)),
                boxShadow: [BoxShadow(color: AppTheme.primary.withValues(alpha: 0.2), blurRadius: 30)],
              ),
              child: Column(
                mainAxisSize: MainAxisSize.min,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Row(
                    children: [
                      const Icon(Icons.auto_awesome, color: AppTheme.secondary, size: 20),
                      const SizedBox(width: 8),
                      const Text('AI SITUATION BRIEF', style: TextStyle(color: AppTheme.secondary, fontWeight: FontWeight.w900, fontSize: 14, letterSpacing: 1.5)),
                    ],
                  ),
                  const SizedBox(height: 4),
                  Text('Generated by Gemini 1.5 Flash', style: TextStyle(color: AppTheme.textSecondary, fontSize: 10)),
                  const SizedBox(height: 16),
                  const Divider(color: AppTheme.surfaceLow),
                  const SizedBox(height: 12),
                  Text(summary, style: const TextStyle(color: Colors.white, fontSize: 14, height: 1.6)),
                  const SizedBox(height: 20),
                  SizedBox(
                    width: double.infinity,
                    child: ElevatedButton(
                      onPressed: () => Navigator.pop(ctx),
                      style: ElevatedButton.styleFrom(
                        backgroundColor: AppTheme.primary, foregroundColor: Colors.black,
                        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                      ),
                      child: const Text('ACKNOWLEDGED', style: TextStyle(fontWeight: FontWeight.bold, letterSpacing: 1)),
                    ),
                  ),
                ],
              ),
            ),
          ),
        );
      }
    } catch (e) {
      if (mounted) setState(() => _isLoadingSummary = false);
      debugPrint('Summary Error: $e');
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppTheme.background,
      body: SafeArea(
        child: Column(
          children: [
            if (widget.showAppBar) _buildTopBar(),
            if (widget.showAppBar) const SizedBox(height: 16),
            _buildMetricsRow(),
            const SizedBox(height: 12),
            // AI Summary Button
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 20.0),
              child: SizedBox(
                width: double.infinity,
                child: OutlinedButton.icon(
                  onPressed: _isLoadingSummary ? null : _showAISummary,
                  style: OutlinedButton.styleFrom(
                    foregroundColor: AppTheme.secondary,
                    side: BorderSide(color: AppTheme.secondary.withValues(alpha: 0.5)),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                    padding: const EdgeInsets.symmetric(vertical: 12),
                  ),
                  icon: _isLoadingSummary 
                    ? const SizedBox(width: 16, height: 16, child: CircularProgressIndicator(strokeWidth: 2, color: AppTheme.secondary))
                    : const Icon(Icons.auto_awesome, size: 16),
                  label: Text(_isLoadingSummary ? 'ANALYZING...' : 'GENERATE AI SITUATION BRIEF', 
                    style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 11, letterSpacing: 1.5)),
                ),
              ),
            ),
            const SizedBox(height: 12),
            Expanded(
              child: _buildAIPriorityList(context),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildTopBar() {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 20.0, vertical: 8.0),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Row(
            children: [
              const Icon(Icons.hub, color: AppTheme.primary),
              const SizedBox(width: 8),
              Text('AIDWISE CORE', style: TextStyle(
                color: AppTheme.textPrimary,
                fontWeight: FontWeight.w900,
                letterSpacing: 1.5,
                fontSize: 18,
                shadows: [Shadow(color: AppTheme.primary.withValues(alpha: 0.5), blurRadius: 10)],
              )),
            ],
          ),
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
            decoration: BoxDecoration(
              color: AppTheme.urgencyLow.withValues(alpha: 0.1),
              borderRadius: BorderRadius.circular(12),
              border: Border.all(color: AppTheme.urgencyLow.withValues(alpha: 0.5)),
            ),
            child: Row(
              children: [
                Container(
                  width: 8, height: 8,
                  decoration: const BoxDecoration(color: AppTheme.urgencyLow, shape: BoxShape.circle),
                ),
                const SizedBox(width: 6),
                const Text('SYSTEM ONLINE', style: TextStyle(color: AppTheme.urgencyLow, fontSize: 10, fontWeight: FontWeight.bold)),
              ],
            ),
          ),
          IconButton(
            icon: const Icon(Icons.logout, color: AppTheme.textSecondary, size: 20),
            onPressed: () => AuthService().signOut(),
          )
        ],
      ),
    );
  }

  Widget _buildMetricsRow() {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 20.0),
      child: Row(
        children: [
          Expanded(child: StreamBuilder<QuerySnapshot>(
            stream: FirebaseFirestore.instance.collection('reports').where('status', isEqualTo: 'Open').snapshots(),
            builder: (ctx, snap) => _buildMetricCard('Unprocessed\nReports', '${snap.data?.docs.length ?? 0}', AppTheme.secondary),
          )),
          const SizedBox(width: 12),
          Expanded(child: StreamBuilder<QuerySnapshot>(
            stream: FirebaseFirestore.instance.collection('reports').where('status', isEqualTo: 'Open').where('urgency', whereIn: ['High', 'Critical']).snapshots(),
            builder: (ctx, snap) => _buildMetricCard('Critical\nHotspots', '${snap.data?.docs.length ?? 0}', AppTheme.urgencyHigh),
          )),
          const SizedBox(width: 12),
          Expanded(child: StreamBuilder<QuerySnapshot>(
            stream: FirebaseFirestore.instance.collection('users').where('role', isEqualTo: 'Volunteer').snapshots(),
            builder: (ctx, snap) => _buildMetricCard('Active\nVolunteers', '${snap.data?.docs.length ?? 0}', AppTheme.primary),
          )),
        ],
      ),
    );
  }

  Widget _buildMetricCard(String title, String count, Color color) {
    return Container(
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(
        color: AppTheme.surface.withValues(alpha: 0.8),
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: color.withValues(alpha: 0.3)),
        boxShadow: AppTheme.glassmorphismShadow,
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(title, style: TextStyle(color: AppTheme.textSecondary, fontSize: 11, fontWeight: FontWeight.w600)),
          const SizedBox(height: 8),
          Text(count, style: TextStyle(
            color: color, 
            fontSize: 24, 
            fontWeight: FontWeight.w900,
            shadows: [Shadow(color: color.withValues(alpha: 0.5), blurRadius: 10)]
          )),
        ],
      ),
    );
  }

  Widget _buildAIPriorityList(BuildContext context) {
    return Container(
      width: double.infinity,
      decoration: BoxDecoration(
        color: AppTheme.surface.withValues(alpha: 0.95),
        border: Border.all(color: AppTheme.primary.withValues(alpha: 0.3)),
      ),
      padding: const EdgeInsets.all(24.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              const Icon(Icons.auto_awesome, color: AppTheme.primary, size: 24),
              const SizedBox(width: 10),
              const Expanded(
                child: Text('AI PRIORITY RANKINGS', 
                  overflow: TextOverflow.ellipsis,
                  style: TextStyle(
                    color: AppTheme.primary, 
                    fontWeight: FontWeight.w900, 
                    letterSpacing: 2.0,
                  )
                ),
              ),
              const SizedBox(width: 8),
              const Text('FIELD REPORTS', style: TextStyle(color: AppTheme.textSecondary, fontSize: 10, fontWeight: FontWeight.bold, letterSpacing: 1.5))
            ],
          ),
          const SizedBox(height: 24),
          Expanded(
            child: StreamBuilder<QuerySnapshot>(
              stream: FirebaseFirestore.instance.collection('reports').where('status', isEqualTo: 'Open').snapshots(),
              builder: (context, snapshot) {
                if (snapshot.connectionState == ConnectionState.waiting) {
                  return const Center(child: CircularProgressIndicator(color: AppTheme.primary));
                }
                
                var allDocs = snapshot.data?.docs ?? [];
                // ONLY show Field Worker reports
                var fieldDocs = allDocs.where((doc) {
                  final data = doc.data() as Map<String, dynamic>;
                  return data['source'] != 'Admin Dashboard';
                }).toList();
                
                if (fieldDocs.isEmpty) {
                  return const Center(
                    child: Text('No active field hotspots detected.', style: TextStyle(color: AppTheme.textSecondary)),
                  );
                }

                // Group by location string to create "Clusters"
                Map<String, List<QueryDocumentSnapshot>> groupedDocs = {};
                for (var doc in fieldDocs) {
                  final data = doc.data() as Map<String, dynamic>;
                  String loc = data['location'] ?? 'Unknown Location';
                  
                  // For GPS coordinates, we truncate slightly so near points cluster together, 
                  // or just group by the exact string if it's a named place/village.
                  // E.g., 'GPS: 28.61, 77.20'
                  if (loc.startsWith('GPS:')) {
                     List<String> parts = loc.replaceAll('GPS:', '').split(',');
                     if (parts.length == 2) {
                        double? lat = double.tryParse(parts[0]);
                        double? lng = double.tryParse(parts[1]);
                        if (lat != null && lng != null) {
                           // Truncate to 2 decimal places implies ~1km clustering radius
                           loc = 'Area Sector: ${lat.toStringAsFixed(2)}, ${lng.toStringAsFixed(2)}';
                        }
                     }
                  }
                  
                  if (!groupedDocs.containsKey(loc)) {
                    groupedDocs[loc] = [];
                  }
                  groupedDocs[loc]!.add(doc);
                }
                
                return ListView.builder(
                  padding: const EdgeInsets.only(bottom: 80), // Padding for bottom nav
                  itemCount: groupedDocs.length,
                  itemBuilder: (context, index) {
                    String locKey = groupedDocs.keys.elementAt(index);
                    List<QueryDocumentSnapshot> clusterDocs = groupedDocs[locKey]!;
                    
                    return Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Padding(
                          padding: const EdgeInsets.only(left: 8.0, top: 8.0, bottom: 12.0),
                          child: Row(
                            children: [
                              const Icon(Icons.share_location, color: AppTheme.primary, size: 16),
                              const SizedBox(width: 8),
                              Flexible(
                                child: Text('CLUSTER: $locKey', 
                                  overflow: TextOverflow.ellipsis,
                                  style: const TextStyle(color: AppTheme.primary, fontWeight: FontWeight.bold, fontSize: 11, letterSpacing: 1.5)
                                ),
                              ),
                            ],
                          ),
                        ),
                        ...clusterDocs.map((doc) {
                          final data = doc.data() as Map<String, dynamic>;
                          String urgencyStr = data['urgency'] ?? 'Medium';
                          Color uColor = urgencyStr == 'High' || urgencyStr == 'Critical' 
                              ? AppTheme.urgencyHigh 
                              : AppTheme.urgencyMedium;
                          
                          return Padding(
                            padding: const EdgeInsets.only(bottom: 16.0),
                            child: _buildHotspotRow(
                              context, 
                              data,
                              uColor,
                              doc.id
                            ),
                          );
                        }),
                        const Divider(color: AppTheme.surfaceLow, height: 32),
                      ],
                    );
                  },
                );
              }
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildHotspotRow(BuildContext context, Map<String, dynamic> data, Color urgencyColor, String reportId) {
    bool hasCoords = data.containsKey('latitude') && data.containsKey('longitude');
    String location = data['location'] ?? 'Unknown Location';
    String need = data['type'] ?? 'General Need';

    return GestureDetector(
      onTap: hasCoords ? () {
        Navigator.push(context, MaterialPageRoute(builder: (_) => ReportDetailMapScreen(
          reportId: reportId,
          reportType: need,
          location: location,
          latitude: (data['latitude'] as num).toDouble(),
          longitude: (data['longitude'] as num).toDouble(),
          urgency: data['urgency'] ?? 'High',
        )));
      } : null,
      child: ClipRRect(
        borderRadius: BorderRadius.circular(12),
        child: BackdropFilter(
          filter: ImageFilter.blur(sigmaX: 16.0, sigmaY: 16.0),
          child: Container(
            padding: const EdgeInsets.all(16),
            decoration: AppTheme.stitchCardWithLeftBorder(urgencyColor),
            child: Row(
              children: [
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Row(
                    children: [
                      Container(
                        width: 8, height: 8,
                        decoration: BoxDecoration(color: urgencyColor, shape: BoxShape.circle, boxShadow: [BoxShadow(color: urgencyColor, blurRadius: 5)]),
                      ),
                      const SizedBox(width: 8),
                      Flexible(child: Text(location, overflow: TextOverflow.ellipsis, style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 16))),
                    ],
                  ),
                  const SizedBox(height: 4),
                  Text('Need: $need', overflow: TextOverflow.ellipsis, style: TextStyle(color: AppTheme.textSecondary, fontSize: 12)),
                ],
              ),
            ),
            const SizedBox(width: 8),
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
              decoration: BoxDecoration(
                color: AppTheme.primary.withValues(alpha: 0.1),
                borderRadius: BorderRadius.circular(8),
                border: Border.all(color: AppTheme.primary.withValues(alpha: 0.3)),
              ),
              child: const Text('98%', style: TextStyle(color: AppTheme.primary, fontWeight: FontWeight.bold)),
            )
          ],
        ),
      ),
    )));
  }
}

class GridPainter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    var paint = Paint()
      ..color = const Color(0xFF1E1E1E)
      ..strokeWidth = 1.0;

    double step = 30.0;
    for (double i = 0; i < size.width; i += step) {
      canvas.drawLine(Offset(i, 0), Offset(i, size.height), paint);
    }
    for (double i = 0; i < size.height; i += step) {
      canvas.drawLine(Offset(0, i), Offset(size.width, i), paint);
    }
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) => false;
}
